crear entredas y salidas de avaluos
Alejandro-Suarez-Rincon/impuestoVehicular pull request #4
Opened 2023-11-15 02:55 UTC by faridcaro666

2023-11-15 04:00 UTC, Camilo-Camargo requested changes

2023-11-15 04:00 UTC, Camilo-Camargo commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalReqDTO.java
> +
cambiar a ingles todos attributos de los dto's.

2023-11-15 23:34 UTC, Alejandro-Suarez-Rincon commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalReqDTO.java
> +    private long id ;
Cambiar de "long" a "Long" para no tener problemas con los tipos de datos de la BD

2023-11-15 23:49 UTC, Alejandro-Suarez-Rincon commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalResDTO.java
> +    private String robado;
los nombres de las variables pararlas a ingles

2023-11-16 00:20 UTC, Alejandro-Suarez-Rincon commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalResDTO.java
> +    private long id ;
cambiar de long a Long

2023-11-16 00:22 UTC, Camilo-Camargo commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalReqDTO.java
> +
[809f2ce](https://github.com/Alejandro-Suarez-Rincon/impuestoVehicular/pull/4/commits/809f2ce03a8d7406b23c3eedcb856393f6f326b9)

2023-11-16 02:29 UTC, Dnvla commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalResDTO.java
> +    private String robado;
comparar los atributos con los de la BD nueva

2023-11-16 02:56 UTC, JAlexYRodriguez commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalReqDTO.java
> +    private String domainextecion;
No poder atributos adicionales a los que están en las entidades o BD, y modificar que queden iguales con los mimos nombres y en ingles

2023-11-16 02:56 UTC, JAlexYRodriguez commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalResDTO.java
> +@AllArgsConstructor
Eliminar el `@AllArgsConstructor`

2023-11-16 02:56 UTC, JAlexYRodriguez commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/UpdateAppraisalResDTO.java
> +    Private String flag;
Este atributo no esta en la BD ¡OJO!

2023-11-16 03:25 UTC, Dnvla approved these changes

2023-11-16 03:32 UTC, JorgeRodriguez09 approved these changes

2023-11-16 03:49 UTC, Camilo-Camargo approved these changes

2023-11-16 03:49 UTC, JAlexYRodriguez approved these changes

2023-11-16 03:49 UTC, Estefania-Araque approved these changes

2023-11-16 03:49 UTC, Estefania-Araque commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalReqDTO.java
> +
Se podría agregar los atributos:
private String type;
private String classVehicle;

2023-11-16 03:49 UTC, Estefania-Araque commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalReqDTO.java
> +
```suggestion



```

2023-11-16 03:49 UTC, Estefania-Araque commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/CreateAppraisalResDTO.java
> +
```suggestion

```

2023-11-16 03:49 UTC, Estefania-Araque commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/UpdateAppraisalReqDTO.java
> +    Private String valueBeforeIva;
Cambiar los "Private", estos se escriben con minúscula "private"

2023-11-16 03:49 UTC, Estefania-Araque commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/UpdateAppraisalReqDTO.java
> +    Private String domainextecion;
Cambiar el "Private", este se escribe con minúscula "private"

2023-11-16 03:49 UTC, Estefania-Araque commented on core/impuestovehicular-ejb/src/main/java/us/codezen/appraisal/dto/UpdateAppraisalResDTO.java
> +    Private String valueBeforeIva;
Cambiar los "Private", estos se escriben con minúscula "private"

2023-11-16 03:50 UTC, Kmoyano approved these changes

2023-11-16 03:57 UTC, AdrianaPiracoca approved these changes

2023-11-16 04:12 UTC, merged

2023-11-16 04:15 UTC, faridcaro666 reviewed
se hizo e arreglo de los DTOS