Crear entradas y salidas vehículo
Alejandro-Suarez-Rincon/impuestoVehicular pull request #9
Opened 2023-11-15 03:34 UTC by Estefania-Araque

2023-11-15 03:59 UTC, Camilo-Camargo requested changes

2023-11-15 03:59 UTC, Camilo-Camargo commented on core/impuestovehicular-ejb/src/main/java/us/codezen/vehicle/dto/CreateVehicleReqDTO.java
> +    Private String antiguo;
cambiar a ingles para todos attributos de los dto's.

2023-11-15 03:59 UTC, Camilo-Camargo commented on core/impuestovehicular-ejb/src/main/java/us/codezen/vehicle/dto/UpdateVehicleResDTO.java
> +    Private String mensaje;  //"El vehiculo se ha actualizado"
```suggestion
    Private String mensaje; 
```

2023-11-15 23:42 UTC, JorgeRodriguez09 approved these changes

2023-11-16 01:55 UTC, Alejandro-Suarez-Rincon approved these changes

2023-11-16 02:26 UTC, JAlexYRodriguez commented on core/impuestovehicular-ejb/src/main/java/us/codezen/vehicle/dto/CreateVehicleReqDTO.java
> +public class CreateVehicleReqDTO(
Agregar los nuevos atributos modificados en la BD

2023-11-16 02:26 UTC, JAlexYRodriguez commented on core/impuestovehicular-ejb/src/main/java/us/codezen/vehicle/dto/CreateVehicleResDTO.java
> +@AllArgsConstructor
Suprimir el `@AllArgsConstructor` ya que el `@Data` lo contiene internamente

2023-11-16 03:27 UTC, merged

2023-11-16 03:54 UTC, Camilo-Camargo commented
a